### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dazadazu** [Lykrast/HarvestersNight#13]
Solution: Remove mod, I imagine its possibly a id conflict... I actually have no idea.

// I'm sorry, Dave.

Time: 3/7/21 4:58 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:149)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:149)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)

-- Affected level --
Details:
	Level name: BIOMESOP
	All players: 1 total; [EntityPlayerMP['Saxby'/31619, l='BIOMESOP', x=-188.36, y=96.00, z=-180.80]]
	Chunk stats: ServerChunkCache: 430 Drop: 0
	Level seed: -7040469993379881599
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-200,94,-344), Chunk: (at 8,5,8 in -13,-22; contains blocks -208,0,-352 to -193,255,-337), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 66979 game time, 66979 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 11873 (now: false), thunder time: 20252 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Lykrast** [comment]
That's missing a lot of information, such as what mods you have (this should be in the full log anyway if you post it instead of just one part) and what were you doing when it crashed.

Also I'm not working on that mod anymore.
